### ISSUE TITLE
Sbt run: unresolved dependencies

### ISSUE THREAD

**Issue by Salvo000** [45deg/Actoverse#4] opened 2018-01-25 19:17 UTC
I would like to study Actoverse and its behaviour. I want to get a quick start as proposed in its readme file.
I don't know scala language. Thus I did all steps of readme of Actoverse that linked me to Actoverse-Scala-Demos. 
Then I cloned Actoverse-Scala-Demos in my machine but it doesn't work.

I'm following the steps of readme file and when i type 'sbt run' using as target Actoverse-Scala-Demo directory, it generate a compilation error of unresolved dependencies.

The Error is the following:

```
[warn] ==== Akka Snapshot Repository: tried
[warn]   http://repo.akka.io/snapshots/com/typesafe/akka/akka-testkit_2.11/2.4-SNAPSHOT/akka-testkit_2.11-2.4-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.akka#akka-actor_2.11;2.4-SNAPSHOT: not found
[warn] 	:: com.typesafe.akka#akka-contrib_2.11;2.4-SNAPSHOT: not found
[warn] 	:: com.typesafe.akka#akka-testkit_2.11;2.4-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.akka:akka-contrib_2.11:2.4-SNAPSHOT (/Users/myusername/.sbt/0.13/staging/37c68d5979975b2c113c/actoverse-scala/build.sbt#L7-15)
[warn] 		  +- actoverse-for-akka:actoverse-for-akka_2.11:1.0
[warn] 		com.typesafe.akka:akka-testkit_2.11:2.4-SNAPSHOT (/Users/myusername/.sbt/0.13/staging/37c68d5979975b2c113c/actoverse-scala/build.sbt#L7-15)
[warn] 		  +- actoverse-for-akka:actoverse-for-akka_2.11:1.0
sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor_2.11;2.4-SNAPSHOT: not found
unresolved dependency: com.typesafe.akka#akka-contrib_2.11;2.4-SNAPSHOT: not found
unresolved dependency: com.typesafe.akka#akka-testkit_2.11;2.4-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1488)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1484)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1519)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1517)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1522)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1516)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1539)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1466)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1418)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] ({https://github.com/45deg/Actoverse-Scala.git}actoverse-scala/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor_2.11;2.4-SNAPSHOT: not found
[error] unresolved dependency: com.typesafe.akka#akka-contrib_2.11;2.4-SNAPSHOT: not found
[error] unresolved dependency: com.typesafe.akka#akka-testkit_2.11;2.4-SNAPSHOT: not found
[error] Total time: 5 s, completed 25-gen-2018 19.00.38

```

If I focused the problem, Sbt tries to download 3 Snapshots (actor,contrib,testkit) that looks like exist if I check on download's website http://repo.akka.io/snapshots/.

I changed the number version of snapshots in file Users/myusername/.sbt/0.13/staging/37c68d5979975b2c113c/actoverse-scala/build.sbt but it give me the same problem with the new snapshot version.

I also tryed to delete cache directories "/Users/myusername/.sbt/0.13/staging/37c68d5979975b2c113c/actoverse-scala" or in "/Users/myusername/.ivy2/cache"
and typed again "sbt run" but I got the same problem.

What can i do ?

Thank a lot.

**Comment by 45deg** [comment] 2018-01-26 05:46
Duplicate of Actoverse-Scala-Demos#1

**Closed by 45deg** 2018-01-26 05:46 UTC
